### ISSUE TITLE
The sel4 thread implementation, what pthread model is ?

### ISSUE THREAD

**Issue by wjhtinger** [seL4/musllibc#13]
Is user space thread, or 1:1 kernel thread(like Linux)? Can the threads be scheduled to different CPU core?

**Comment by kent-mcleod** [comment]
seL4 threads are explained in the [manual](https://sel4.systems/Info/Docs/seL4-manual-latest.pdf).  All verified seL4 configurations are single core. There is a multicore configuration that is unverified. In this configuration, seL4 threads are configured with a core affinity and a user scheduler can move threads between different cores by changing this affinity. If the MCS kernel is being used, core affinities are instead associated with SchedulingContext objects. When a thread is attached to a SC object it will execute on the corresponding core. With a SC donation mechanism over Endpoint objects, a receiving thread can migrate to the same core as the calling thread when handling an endpoint call and then migrate to another core when handling a request for a different client.

POSIX pthreads aren't implemented by seL4. User level system libraries can be used to implement a pthread API on top of seL4 threads but there aren't any examples of this in the current set of foundation libraries AFAIK.
