### ISSUE TITLE
Dynamic linking of NEEDED with absolute path differs than that of glibc

### ISSUE THREAD

**Issue by fzakaria** [seL4/musllibc#16]
Hello! First off, thank you for this project.

I am working on a tool that takes all the _NEEDED_ from downstream shared object dependencies and _lifts_ them to the top executable. I then change the _NEEDED_ in the top executable to be **absolute paths**. This seems to work as expected in _glibc_.

Please use this example for demonstrations:

Here I have two shared objects **libbar** and **libfoo**, where _foo_ depends on _bar_.
```
❯ patchelf --print-needed libbar.so
libc.so.6
❯ patchelf --print-soname libbar.so
libbar.so

❯ patchelf --print-needed libfoo.so
libbar.so
libc.so.6
```

I then add **libbar** and **libfoo** to another executable  but reference them in _NEEDED_ with explicit paths.

```
patchelf --print-needed tests/scratch/replace-add-needed/simple
/some-fixed-path/libbar.so
/some-fixed-path/libfoo.so
/lib/x86_64-linux-gnu/libc.so.6
```

_glibc_ seems to happily link this and the executable runs.
```
ldd ./tests/scratch/replace-add-needed/simple
	linux-vdso.so.1 (0x00007ffc98d98000)
	/some-fixed-path/libbar.so (0x00007f269b6d3000)
	/some-fixed-path/llibfoo.so (0x00007f269b6ce000)
	/lib/x86_64-linux-gnu/libc.so.6 (0x00007f269b509000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f269c6e3000)
```

If I do the same however with _musl_ it doesn't seem to link and complains about not finding **libbar.so**

```
ldd ./tests/scratch/replace-add-needed/simple 
	/lib/ld-musl-x86_64.so.1 (0x7f04dd7cd000)
	/some-fixed-path/libbar.so (0x7f04dc7bf000)
	/some-fixed-path/libfoo.so (0x7f04dc7ba000)
	libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7f04dd7cd000)
Error loading shared library libbar.so: No such file or directory (needed by /some-fixed-path/libfoo.so)
```

CC @trws

**Comment by trws** [comment]
Looks like this is because of the shortname assignment behavior from: https://github.com/rofl0r/musl/commit/0420b874465db7544a9e1f320969b4920c9405d8

This is clearly safer than what it was doing before that, but would musl be open to either:

1. Using the contents of DT_SONAME if set, which matches the behavior of glibc at least from observation, or
2. Using a shortname based on the `basename` of the path even for path-based loading?

**Comment by kent-mcleod** [comment]
Hi @fzakaria and @trws, this repository is a musl fork and isn't affiliated with the upstream project.  This fork only targets seL4 microkernel userspaces where it's used more as a freestanding C library than a standard compliant hosted implementation and as such, the dynamic linker isn't used. 

I see that you have already posted your requests to the official musl mailing list where I'd expect you would get a proper response.

**Comment by fzakaria** [comment]
That was my mistake - I"m sorry. I opened the issue on the mailing list instead.

**Comment by kent-mcleod** [comment]
It's no problem.
