### ISSUE TITLE
Improper Linking on x86_64 Target when Compiling w/ M1 MAC

### ISSUE THREAD

**Issue by chrisguikema** [seL4/musllibc#20]
I know compiling with ARM hosts isn't technically supported, but I've been able to compile images with only a single change to the kernel's gcc.cmake file.

Compiling the `adder` application for x86_64 gives images which fail when simulated and run on x86 hardware.

```
Caught cap fault in send phase at address 0
while trying to handle:
unknown syscall 0x10
in thread 0xffffff801fc08400 "rootserver" at address 0x41b9a5
```

Doing a decompilation, the instructions at `0x41b9a5` are:

```
000000000041b998 <__set_thread_area>:
  41b998:	48 89 fe             	mov    %rdi,%rsi
  41b99b:	bf 02 10 00 00       	mov    $0x1002,%edi
  41b9a0:	b8 9e 00 00 00       	mov    $0x9e,%eax
  41b9a5:	0f 05                	syscall 
  41b9a7:	c3                   	retq   
```

This tracks with the error print where seL4 can't handle the `syscall`.

The interesting this is that when decompiling a working image (compiled on an x86 host), the `__set_thread_area` function is this:

```
000000000041c28a <__set_thread_area>:
  41c28a:	48 89 fe             	mov    %rdi,%rsi
  41c28d:	bf cd 00 00 00       	mov    $0xcd,%edi
  41c292:	50                   	push   %rax
  41c293:	31 c0                	xor    %eax,%eax
  41c295:	ff 15 65 d2 b8 05    	call   *0x5b8d265(%rip)        # 5fa9500 <__sysinfo>
  41c29b:	5a                   	pop    %rdx
  41c29c:	c3                   	ret    
```

Which tracks with the [x86_64_sel4](https://github.com/seL4/musllibc/blob/sel4/src/internal/x86_64_sel4/syscall.s) implementation of `syscall`.

I'm trying to get a working musllibc build directory to compare against, but does anyone have any ideas?

**Comment by chrisguikema** [comment]
The only thing I can see is this error during the build:

```
[75/243] Invoking muslc build system
sed: couldn't open temporary file ./sed8kIn4v: Permission denied
```

Then the `build-temp` directory doesn't contain a `config.makbak` file, and `config.mak` still compiles for `x86_64` instead of `x86_64_sel4`.

**Comment by chrisguikema** [comment]
Found a fix!

```
chrisguikema: ~/seL4/camkes/projects/musllibc [(no branch)] $ git diff
diff --git a/Makefile b/Makefile
index 5973d09f..7c8b863b 100644
--- a/Makefile
+++ b/Makefile
@@ -68,7 +68,7 @@ build_muslc:
        # Only print output if there's an error as configure is quite noisy
        # Also need to update the ARCH in the config.mak file configure generates
        [ "`cat configure_line 2>&1`" != "${configure_line}" ] && \
-               ${SOURCE_DIR}/configure ${configure_line} 2>&1 > config.log || cat config.log  && sed -ibak 's/^ARCH = \(.*\)/ARCH = \1_sel4/' config.mak || true
+               ${SOURCE_DIR}/configure ${configure_line} 2>&1 > config.log || cat config.log && mv config.mak config.makbak && sed 's/^ARCH = \(.*\)/ARCH = \1_sel4/' config.makbak >> config.mak || true
```

This essentially does the exact same thing as `sed -i` but without the strange permissions issues I was seeing

**Comment by kent-mcleod** [comment]
This fix seems fine to me, but do you know why the sed -i option doesn't work in your environment? The lack of permissions to write the new file could cause issues in other cases too.

**Comment by chrisguikema** [comment]
I was getting the docker containers compiled on an M1 MacBook. To be honest, I have no idea why I was having permissions issues. The version of `sed` was identical to the containers on the x86 host. I think @lsf37 was going to investigate the containers further. Maybe he'll have better luck

**Comment by lsf37** [comment]
Yes, I'm planning to look into it. I might take a while, moving house next week and things are a bit chaotic.

**Comment by chrisguikema** [comment]
That's not a problem, since I have the containers working. If/when they're mainlined, I'll happily update :)

**Comment by chrisguikema** [comment]
Someone on the mailing list was also seeing this issue. Can I make a PR to fix this for anyone in the future?

**Comment by kent-mcleod** [comment]
Is this when building natively on a M1 Mac or when running Arm Linux vm on M1 Mac? I think the change should be fine in any case

**Comment by chrisguikema** [comment]
I see it when running in the Docker container. The mailing list just said "sel4 using qemu under macosx...using Docker as the build environment". I'm not sure if that's an Arm/x86 issue or what.

**Comment by kent-mcleod** [comment]
I see.  I'm hoping its caused by the gRPC fs layer that docker on mac uses to mount a host directory from macos into the Linux VM.  Some related issues: https://github.com/docker/for-mac/issues/4964.  Are you using the gRPC FUSE transport or the libvirt transport for mounts from macos into the container? (It's an option somewhere in the settings in docker desktop)

**Comment by chrisguikema** [comment]
Looks like if I turn off a few options "Use the new virtualization framework, Enable VirtioFS accelerated directory sharing", I don't need to do this. Downside is that it drastically increases the build time.

**Comment by kent-mcleod** [comment]
> Looks like if I turn off a few options "Use the new virtualization framework, Enable VirtioFS accelerated directory sharing", I don't need to do this. Downside is that it drastically increases the build time.

I've been using the virtioFS and the virtualization framework for my builds on macos and don't get the permission issue for what it is worth.

**Comment by chrisguikema** [comment]
Might depend on the version of Docker desktop you're using. When I upgraded to the latest version, I didn't see the warning anymore. That doesn't necessarily mean the runtime issue went away, but its something, at least.
